version: "3.8"

services:
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    command:
      - "--api.insecure=true" # Enable the dashboard (not for production)
      - "--providers.file.directory=/etc/traefik/config" # Load dynamic configuration
      - "--entrypoints.web.address=:80" # HTTP entry point
      - "--entrypoints.websecure.address=:443" # HTTPS entry point
    ports:
      - "80:80" # Expose HTTP
      - "443:443" # Expose HTTPS
      - "8080:8080" # Expose the dashboard
    volumes:
      - /home/ubuntu/traefik:/etc/traefik # Mount configuration directory
    networks:
      - web

networks:
  web:
    driver: bridge
